# _data/sources.yaml

# Wind-to-Hydrogen Forecasting
- id: doi:10.1016/j.ijhydene.2025.152853
  image: images/publications/2026-doha-h2.jpg

- id: doi:10.1016/j.uclim.2025.102669
  image: images/publications/2025-laeeq-grid.jpg

- id: doi:10.1016/j.mechmachtheory.2025.106286
  image: images/publications/2025-zheng-stiffness.jpg

# Physics-Informed Cable Monitoring
- id: doi:10.3390/a18100600
  image: images/publications/2026-zaki-CNN-LSTM.png
  
# Federated Learning for Wind
- id: doi:10.1115/es2025-156364
  image: images/publications/2025-william-FL.png

# IVT Control for Tidal Energy
- id: doi:10.1109/TMECH.2024.3398534
  image: images/publications/ivt-control.jpg



# LSTM Wind Forecasting
- id: doi:10.3390/a18040206
  image: images/publications/wind-forecasting.jpg
 
